name: stonekaiju3
favicon: null
layout_spectrum: 0.3615737946238369
typography_spectrum: 0.46926
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#110101'
    - '#ff0506'
    - '#833b3c'
    - '#e1c0d1'
  brandStrength: 0.5625
  lightness: 0.0625
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
