name: stonekaiju3
favicon: null
layout_spectrum: 0.3615737946238369
typography_spectrum: 0.25777
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d081c'
    - '#ffffff'
    - '#1e3cf2'
    - '#b02393'
    - '#85d1f5'
  brandStrength: 0.0625
  lightness: 0.0625
  saturation: 0.1875
  rhythmicContrast: 0
purpose: []
