name: stonekaiju3
favicon: null
layout_spectrum: 0.3615737946238369
typography_spectrum: 0.09368691593408585
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8004601653665304
  lightness: 0.5677721416577697
  saturation: 0.9799098665826023
  rhythmicContrast: 0.9472859539091587
purpose: []
